[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301
  force = true