import { CarsDataType, Country } from '../types/catalog'

export const countries: Country[] = [
    { id: 'china', name: 'Китай' },
    { id: 'japan', name: 'Япония' },
    { id: 'korea', name: 'Корея' },
    { id: 'europe', name: 'Европа' },
]

export const categories = [
    'Все',
    'Кроссоверы',
    'Седаны',
    'Электромобили',
    'Минивэны',
]

export const priceRanges = [
    'Все цены',
    'До 2 млн',
    '2-3 млн',
    '3-4 млн',
    'От 4 млн',
]

export const carsData: CarsDataType = {
    china: [
        {
            id: '1',
            brand: 'BYD',
            model: 'Han',
            year: 2023,
            category: 'Кроссоверы',
            price: 2355000,
            images: [
                '/img/catalog/china/BYD-Han/1.jpg',
                '/img/catalog/china/BYD-Han/2.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 2.0,
                fuelType: 'Hybrid',
                horsePower: 192,
                transmission: 'Робот',
                driveType: 'Полный',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '2',
            brand: 'BYD',
            model: 'Song-Plus DM-I 110km',
            year: 2021,
            category: 'Кроссоверы',
            price: 1888000,
            equipment: 'Пред Максимальная комплектация',
            images: [
                '/img/catalog/china/BYD-Song-Plus/1.jpg',
                '/img/catalog/china/BYD-Song-Plus/2.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Hybrid',
                horsePower: 110,
                transmission: 'Вариатор',
                driveType: 'Передний ',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '3',
            brand: 'CHANGAN',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 2495000,
            images: [
                '/img/catalog/china/CHANGAN-Uni-K/19.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/18.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 2.0,
                fuelType: 'Turbo',
                horsePower: 233,
                transmission: 'Автомат',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Панорамный люк',
                    'Подогрев и обдув сидений',
                    'Память и обогрев зеркал',
                ],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '4',
            brand: 'Chery',
            model: 'Arrizo8',
            year: 2021,
            category: 'Седаны',
            price: 2165000,
            images: [
                '/img/catalog/china/Chery-Arrizo8/1.jpg',
                '/img/catalog/china/Chery-Arrizo8/2.jpg',
            ],
            specs: {
                mileage: 18000,
                engineVolume: 1.6,
                fuelType: 'Turbo',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '5',
            brand: 'Geely',
            model: 'Coolray',
            year: 2021,
            category: 'Кроссоверы',
            price: 1413000,
            images: [
                '/img/catalog/china/Geely-Coolray/1.jpg',
                '/img/catalog/china/Geely-Coolray/2.jpg',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Turbo',
                horsePower: 177,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '6',
            brand: 'Geely',
            model: 'Emgrand',
            year: 2021,
            category: 'Седаны',
            price: 1172500,
            images: [
                '/img/catalog/china/Geely-Emgrand/1.jpg',
                '/img/catalog/china/Geely-Emgrand/2.jpg',
            ],
            specs: {
                mileage: 25000,
                engineVolume: 1.5,
                fuelType: 'Petrol',
                horsePower: 114,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '7',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 2257000,
            images: [
                '/img/catalog/china/Haval-Dargo/1.jpg',
                '/img/catalog/china/Haval-Dargo/2.jpg',
            ],
            specs: {
                mileage: 40000,
                engineVolume: 2.0,
                fuelType: 'Turbo',
                horsePower: 211,
                transmission: 'Робот',
                driveType: '4WD',
                features: ['Максимальная комплектация'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '8',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 1914000,
            images: [
                '/img/catalog/china/Haval-Dargo_Avial/1.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/2.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 1.5,
                fuelType: 'Turbo',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Круиз-контроль',
                    'Панорамный люк',
                    'Подогрев руля',
                    'Подогрев и обдув сидений',
                    'Обогрев зеркал',
                ],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '9',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/china/Haval-M6-mkpp/1.webp',
                '/img/catalog/china/Haval-M6-mkpp/2.webp',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Turbo',
                horsePower: 0,
                transmission: 'Механика',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '10',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1980000,
            images: [
                '/img/catalog/china/Haval-M6-robot/6.webp',
                '/img/catalog/china/Haval-M6-robot/7.webp',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Turbo',
                horsePower: 150,
                transmission: 'Робот',
                driveType: 'Передний',
                features: ['Максимальная комплектация'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '11',
            brand: 'Oshan',
            model: 'X5',
            year: 2024,
            category: 'Кроссоверы',
            price: 1350000,
            images: [
                '/img/catalog/china/Oshan-X5/1.jpg',
                '/img/catalog/china/Oshan-X5/2.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Turbo',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '12',
            brand: 'Changan',
            model: 'CS75PLUS',
            year: 2022,
            category: 'Кроссоверы',
            price: 1715000,
            images: [
                '/img/catalog/china/drom/Changan-CS75Plus/1.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/2.jpg',
            ],
            specs: {
                mileage: 19000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Белый',
                generation: '2 поколение',
                features: ['1.5 AT Exclusive'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '13',
            brand: 'GAC',
            model: 'Trumpchi M6',
            year: 2021,
            category: 'Минивэны',
            price: 0,
            images: [
                '/img/catalog/china/drom/Gac-M6/1.jpg',
                '/img/catalog/china/drom/Gac-M6/2.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Белый',
                generation: '1 поколение',
                features: ['1.5T DCT 2WD 270T Premium Edition 6 seats'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '14',
            brand: 'Exeed',
            model: 'LX',
            year: 2022,
            category: 'Кроссоверы',
            price: 1900000,
            images: [
                '/img/catalog/china/drom/Exeed-LX/1.jpg',
                '/img/catalog/china/drom/Exeed-LX/2.jpg',
            ],
            specs: {
                mileage: 15000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Черный',
                generation: '1 поколение, рестайлинг',
                features: ['Zhuifeng 1.6T DCT Goddess 300T'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '15',
            brand: 'Geely',
            model: 'Mongaro',
            year: 2021,
            category: 'Кроссоверы',
            price: 0,
            images: [
                '/img/catalog/china/drom/Gelly-Mongaro/1.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/2.jpg',
            ],
            specs: {
                mileage: 44000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 235,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Черный',
                generation: '1 поколение',
                features: ['Xingyue L 2.0 AT Distinguished'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '16',
            brand: 'Geely',
            model: 'Tugella',
            year: 2021,
            category: 'Кроссоверы',
            price: 1950000,
            images: [
                '/img/catalog/china/drom/Gelly-Tugella/1.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/2.jpg',
            ],
            specs: {
                mileage: 17000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение, рестайлинг',
                features: ['Xingyue S 2.0 DCT Lightning'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '17',
            brand: 'TANK',
            model: '300',
            year: 2021,
            category: 'Внедорожники',
            price: 0,
            images: [
                '/img/catalog/china/drom/TANK-300/1.jpg',
                '/img/catalog/china/drom/TANK-300/2.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 227,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Белый',
                generation: '1 поколение',
                features: ['2.0T AT 4WD Off-Road Conqueror'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '18',
            brand: 'Changan',
            model: 'Uni-T',
            year: 2021,
            category: 'Кроссоверы',
            price: 0, // Укажите цену, если она известна
            images: [
                '/img/catalog/china/drom/Unit-T-drom/1.jpg',
                '/img/catalog/china/drom/Unit-T-drom/2.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение',
                features: ['1.5 AMT'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '19',
            brand: 'Changan',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 0, // Укажите цену, если она известна
            images: [
                '/img/catalog/china/drom/Uni-K-drom/1.jpg',
                '/img/catalog/china/drom/Uni-K-drom/2.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 233,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Голубой',
                generation: '1 поколение',
                features: ['2.0 AT Premium'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    japan: [],
    korea: [],
    europe: [],
}
