import { CarsDataType, Country } from '../types/catalog'

export const countries: Country[] = [
    { id: 'china', name: 'Китай' },
    { id: 'japan', name: 'Япония' },
    { id: 'korea', name: 'Корея' },
    { id: 'europe', name: 'Европа' },
]

export const categories = [
    'Все',
    'Кроссоверы',
    'Седаны',
    'Электромобили',
    'Минивэны',
]

export const priceRanges = [
    'Все цены',
    'До 2 млн',
    '2-3 млн',
    '3-4 млн',
    'От 4 млн',
]

export const carsData: CarsDataType = {
    china: [
        {
            id: '1',
            brand: 'BYD',
            model: 'Han',
            year: 2023,
            category: 'Кроссоверы',
            price: 2355000,
            images: [
                '/img/catalog/china/BYD-Han/1.jpg',
                '/img/catalog/china/BYD-Han/2.jpg',
                '/img/catalog/china/BYD-Han/3.jpg',
                '/img/catalog/china/BYD-Han/4.jpg',
                '/img/catalog/china/BYD-Han/5.jpg',
                '/img/catalog/china/BYD-Han/6.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 2.0,
                fuelType: 'Hybrid',
                horsePower: 192,
                transmission: 'Робот',
                driveType: 'Полный',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '2',
            brand: 'BYD',
            model: 'Song-Plus DM-I',
            year: 2021,
            category: 'Кроссоверы',
            price: 1888000,
            equipment: 'Пред Максимальная комплектация',
            images: [
                '/img/catalog/china/BYD-Song-Plus/1.jpg',
                '/img/catalog/china/BYD-Song-Plus/2.jpg',
                '/img/catalog/china/BYD-Song-Plus/3.jpg',
                '/img/catalog/china/BYD-Song-Plus/4.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Hybrid',
                horsePower: 110,
                transmission: 'Вариатор',
                driveType: 'Передний ',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '3',
            brand: 'CHANGAN',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 2495000,
            images: [
                '/img/catalog/china/CHANGAN-Uni-K/19.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/18.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 233,
                transmission: 'Автомат',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Панорамный люк',
                    'Подогрев и обдув сидений',
                    'Память и обогрев зеркал',
                ],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '4',
            brand: 'Chery',
            model: 'Arrizo8',
            year: 2021,
            category: 'Седаны',
            price: 2165000,
            images: [
                '/img/catalog/china/Chery-Arrizo8/1.jpg',
                '/img/catalog/china/Chery-Arrizo8/2.jpg',
            ],
            specs: {
                mileage: 18000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '5',
            brand: 'Geely',
            model: 'Coolray',
            year: 2021,
            category: 'Кроссоверы',
            price: 1413000,
            images: [
                '/img/catalog/china/Geely-Coolray/1.jpg',
                '/img/catalog/china/Geely-Coolray/2.jpg',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 177,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '6',
            brand: 'Geely',
            model: 'Emgrand',
            year: 2021,
            category: 'Седаны',
            price: 1172500,
            images: [
                '/img/catalog/china/Geely-Emgrand/1.jpg',
                '/img/catalog/china/Geely-Emgrand/2.jpg',
            ],
            specs: {
                mileage: 25000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 114,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '7',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 2257000,
            images: [
                '/img/catalog/china/Haval-Dargo/1.jpg',
                '/img/catalog/china/Haval-Dargo/2.jpg',
            ],
            specs: {
                mileage: 40000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 211,
                transmission: 'Робот',
                driveType: '4WD',
                features: ['Максимальная комплектация'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '8',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 1914000,
            images: [
                '/img/catalog/china/Haval-Dargo_Avial/1.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/2.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Круиз-контроль',
                    'Панорамный люк',
                    'Подогрев руля',
                    'Подогрев и обдув сидений',
                    'Обогрев зеркал',
                ],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '9',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/china/Haval-M6-mkpp/1.webp',
                '/img/catalog/china/Haval-M6-mkpp/2.webp',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 0,
                transmission: 'Механика',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '10',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1980000,
            images: [
                '/img/catalog/china/Haval-M6-robot/6.webp',
                '/img/catalog/china/Haval-M6-robot/7.webp',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 150,
                transmission: 'Робот',
                driveType: 'Передний',
                features: ['Максимальная комплектация'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '11',
            brand: 'Oshan',
            model: 'X5',
            year: 2024,
            category: 'Кроссоверы',
            price: 1350000,
            images: [
                '/img/catalog/china/Oshan-X5/1.jpg',
                '/img/catalog/china/Oshan-X5/2.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '12',
            brand: 'Changan',
            model: 'CS75PLUS',
            year: 2022,
            category: 'Кроссоверы',
            price: 1715000,
            images: [
                '/img/catalog/china/drom/Changan-CS75Plus/1.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/2.jpg',
            ],
            specs: {
                mileage: 19000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Белый',
                generation: '2 поколение',
                features: ['1.5 AT Exclusive'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '13',
            brand: 'GAC',
            model: 'M6 Trumpchi',
            year: 2021,
            category: 'Минивэны',
            price: 1750000,
            images: [
                '/img/catalog/china/drom/Gac-M6/1.jpg',
                '/img/catalog/china/drom/Gac-M6/2.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Белый',
                generation: '1 поколение',
                features: ['1.5T DCT 2WD 270T Premium Edition 6 seats'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '14',
            brand: 'Exeed',
            model: 'LX',
            year: 2022,
            category: 'Кроссоверы',
            price: 1900000,
            images: [
                '/img/catalog/china/drom/Exeed-LX/1.jpg',
                '/img/catalog/china/drom/Exeed-LX/2.jpg',
            ],
            specs: {
                mileage: 15000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Черный',
                generation: '1 поколение, рестайлинг',
                features: ['Zhuifeng 1.6T DCT Goddess 300T'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '15',
            brand: 'Geely',
            model: 'Mongaro',
            year: 2021,
            category: 'Кроссоверы',
            price: 2800000,
            images: [
                '/img/catalog/china/drom/Gelly-Mongaro/1.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/2.jpg',
            ],
            specs: {
                mileage: 44000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 235,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Черный',
                generation: '1 поколение',
                features: ['Xingyue L 2.0 AT Distinguished'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '16',
            brand: 'Geely',
            model: 'Tugella',
            year: 2021,
            category: 'Кроссоверы',
            price: 1950000,
            images: [
                '/img/catalog/china/drom/Gelly-Tugella/1.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/2.jpg',
            ],
            specs: {
                mileage: 17000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение, рестайлинг',
                features: ['Xingyue S 2.0 DCT Lightning'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '17',
            brand: 'TANK',
            model: '300',
            year: 2021,
            category: 'Внедорожники',
            price: 3020000,
            images: [
                '/img/catalog/china/drom/TANK-300/1.jpg',
                '/img/catalog/china/drom/TANK-300/2.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 227,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Белый',
                generation: '1 поколение',
                features: ['2.0T AT 4WD Off-Road Conqueror'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '18',
            brand: 'Changan',
            model: 'Uni-T',
            year: 2021,
            category: 'Кроссоверы',
            price: 1580000,
            images: [
                '/img/catalog/china/drom/Unit-T-drom/1.jpg',
                '/img/catalog/china/drom/Unit-T-drom/2.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение',
                features: ['1.5 AMT'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '19',
            brand: 'Changan',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 2399000,
            images: [
                '/img/catalog/china/drom/Uni-K-drom/1.jpg',
                '/img/catalog/china/drom/Uni-K-drom/2.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 233,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Голубой',
                generation: '1 поколение',
                features: ['2.0 AT Premium'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    japan: [
        {
            id: '26',
            brand: 'Toyota',
            model: 'Corolla Cross',
            year: 2022,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/jp/Corolla-Cross/1.jpg',
                '/img/catalog/jp/Corolla-Cross/2.jpg',
            ],
            specs: {
                mileage: 5000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 152,
                transmission: 'Вариатор (CVT)',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '27',
            brand: 'Eclipse',
            model: 'Cross',
            year: 2020,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/jp/Eclips-Cross/1.jpg',
                '/img/catalog/jp/Eclips-Cross/2.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 170,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Серый',
                generation: '1 поколение',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '28',
            brand: 'Toyota',
            model: 'Harrier',
            year: 2021,
            category: 'Кроссоверы',
            price: 3802800,
            images: [
                '/img/catalog/jp/Harrier/1.jpg',
                '/img/catalog/jp/Harrier/2.jpg',
            ],
            specs: {
                mileage: 15000,
                engineVolume: 2.5,
                fuelType: 'Гибрид',
                horsePower: 178,
                transmission: 'Вариатор (CVT)',
                driveType: '4WD',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '29',
            brand: 'Honda',
            model: 'Breeze',
            year: 2021,
            category: 'Кроссоверы',
            price: 2400000,
            images: [
                '/img/catalog/jp/Honda-breeze/1.jpg',
                '/img/catalog/jp/Honda-breeze/2.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
                color: 'Белый',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '30',
            brand: 'Honda',
            model: 'Civic',
            year: 2021,
            category: 'Седаны',
            price: 1819500,
            images: [
                '/img/catalog/jp/Honda-Civic/1.jpg',
                '/img/catalog/jp/Honda-Civic/2.jpg',
            ],
            specs: {
                mileage: 42000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 182,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '31',
            brand: 'Honda',
            model: 'Civic Hatchback',
            year: 2021,
            category: 'Хэтчбеки',
            price: 1931000,
            images: [
                '/img/catalog/jp/Honda-Civic-HatchBack/1.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/2.jpg',
            ],
            specs: {
                mileage: 25000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 177,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '32',
            brand: 'Honda',
            model: 'CR-V',
            year: 2021,
            category: 'Кроссоверы',
            price: 2084000,
            images: [
                '/img/catalog/jp/Honda-CR-V/1.jpg',
                '/img/catalog/jp/Honda-CR-V/2.jpg',
            ],
            specs: {
                mileage: 33000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '33',
            brand: 'Honda',
            model: 'Fit',
            year: 2021,
            category: 'Субкомпактные',
            price: 1365000,
            images: [
                '/img/catalog/jp/Honda-Fit/1.jpg',
                '/img/catalog/jp/Honda-Fit/2.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 131,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '34',
            brand: 'Honda',
            model: 'Odyssey',
            year: 2021,
            category: 'Минивэны',
            price: 3290500,
            images: [
                '/img/catalog/jp/Honda-Odyssey/1.jpg',
                '/img/catalog/jp/Honda-Odyssey/2.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 146,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '35',
            brand: 'Honda',
            model: 'CR-V',
            year: 2021,
            category: 'Кроссоверы',
            price: 2200000,
            images: [
                '/img/catalog/jp/Honda-C-RV/1.jpg',
                '/img/catalog/jp/Honda-C-RV/2.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
                features: ['пред максимальная комплектация'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '36',
            brand: 'Honda',
            model: 'Fit',
            year: 2021,
            category: 'Субкомпактные',
            price: 1365000,
            images: [
                '/img/catalog/jp/Honda-Fit/1.jpg',
                '/img/catalog/jp/Honda-Fit/2.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 131,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '37',
            brand: 'Honda',
            model: 'Odyssey',
            year: 2021,
            category: 'Минивэны',
            price: 3290500,
            images: [
                '/img/catalog/jp/Honda-Odyssey/1.jpg',
                '/img/catalog/jp/Honda-Odyssey/2.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 146,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '38',
            brand: 'Honda',
            model: 'Accord',
            year: 2021,
            category: 'Седаны',
            price: 1950000,
            images: [
                '/img/catalog/jp/Hоnda-Accord/1.jpg',
                '/img/catalog/jp/Hоnda-Accord/2.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 194,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '39',
            brand: 'Nissan',
            model: 'Sylphy',
            year: 2021,
            category: 'Седаны',
            price: 1710500,
            images: [
                '/img/catalog/jp/Nissan-Sylphy/1.jpg',
                '/img/catalog/jp/Nissan-Sylphy/2.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 135,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '40',
            brand: 'Nissan',
            model: 'X-Trail',
            year: 2021,
            category: 'Кроссоверы',
            price: 3100000,
            images: [
                '/img/catalog/jp/Nissan-X-Trail/1.jpg',
                '/img/catalog/jp/Nissan-X-Trail/2.jpg',
            ],
            specs: {
                mileage: 2000,
                engineVolume: 1.5,
                fuelType: 'Гибрид',
                horsePower: 144,
                transmission: 'АКПП',
                driveType: '4WD',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '41',
            brand: 'Subaru',
            model: 'Forester',
            year: 2021,
            category: 'Кроссоверы',
            price: 2575500,
            images: [
                '/img/catalog/jp/Subaru-Forester/1.jpg',
                '/img/catalog/jp/Subaru-Forester/2.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 154,
                transmission: 'Вариатор',
                driveType: '4WD',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '42',
            brand: 'Toyota',
            model: 'Camry',
            year: 2021,
            category: 'Седаны',
            price: 2640000,
            images: [
                '/img/catalog/jp/Toyota-Camry/1.jpg',
                '/img/catalog/jp/Toyota-Camry/2.jpg',
            ],
            specs: {
                mileage: 32000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 178,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '43',
            brand: 'Toyota',
            model: 'CH-R',
            year: 2021,
            category: 'Кроссоверы',
            price: 2009000,
            images: [
                '/img/catalog/jp/Toyota-CH-R/1.jpg',
                '/img/catalog/jp/Toyota-CH-R/2.jpg',
            ],
            specs: {
                mileage: 42000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '44',
            brand: 'Toyota',
            model: 'Harrier',
            year: 2021,
            category: 'Кроссоверы',
            price: 3990000,
            images: [
                '/img/catalog/jp/Toyota-Harrier-new/1.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/2.jpg',
            ],
            specs: {
                mileage: 0,
                engineVolume: 2.5,
                fuelType: 'Гибрид',
                horsePower: 178,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '45',
            brand: 'Toyota',
            model: 'RAV-4 Fashion',
            year: 2020,
            category: 'Кроссоверы',
            price: 2950000,
            images: [
                '/img/catalog/jp/Rav4-2020/1.jpg',
                '/img/catalog/jp/Rav4-2020/2.jpg',
            ],
            specs: {
                mileage: 37000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Белый',
                generation: '5 поколение',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '46',
            brand: 'Toyota',
            model: 'Wildlander',
            year: 2021,
            category: 'Кроссоверы',
            price: 2716000,
            images: [
                '/img/catalog/jp/Toyota-Wildlander/1.jpg',
                '/img/catalog/jp/Toyota-Wildlander/2.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Белый',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    korea: [
        {
            id: '44',
            brand: 'Hyundai',
            model: 'Elantra',
            year: 2021,
            category: 'Седаны',
            price: 2140000,
            images: [
                '/img/catalog/korea/Hyundai-Elantra/1.jpg',
                '/img/catalog/korea/Hyundai-Elantra/2.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 115,
                transmission: 'Вариатор',
                driveType: 'Передний',
                color: 'Синий',
            },

            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '45',
            brand: 'Hyundai',
            model: 'Tucson',
            year: 2021,
            category: 'Кроссоверы',
            price: 1930000,
            images: [
                '/img/catalog/korea/Hyundai-Tucson/1.jpg',
                '/img/catalog/korea/Hyundai-Tucson/2.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 200,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '46',
            brand: 'KIA',
            model: 'K5',
            year: 2021,
            category: 'Седаны',
            price: 2190000,
            images: [
                '/img/catalog/korea/KIA-K5/1.jpg',
                '/img/catalog/korea/KIA-K5/2.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 240,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Серый',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    europe: [
        {
            id: '20',
            brand: 'BMW',
            model: 'X1',
            year: 2021,
            category: 'Кроссоверы',
            price: 2332500,
            images: [
                '/img/catalog/eu/BMW-X1/1.jpg',
                '/img/catalog/eu/BMW-X1/2.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 140,
                transmission: 'АКПП-робот (7 ступеней)',
                driveType: 'Передний',
                color: '',
                generation: 'sDrive 20Li SAT Exclusive',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '21',
            brand: 'Mercedes-Benz',
            model: 'C-Class',
            year: 2021,
            category: 'Седаны',
            price: 2950000,
            images: [
                '/img/catalog/eu/Mercedes-Benz-C-Class/1.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/2.jpg',
            ],
            specs: {
                mileage: 45000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 156,
                transmission: 'АКПП автомат',
                driveType: 'Задний',
                color: '',
                generation: '200L Fashion Sport',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '22',
            brand: 'Mercedes-Benz',
            model: 'GLB',
            year: 2021,
            category: 'Кроссоверы',
            price: 3350000,
            images: [
                '/img/catalog/eu/Mercedes-Benz-GLB/1.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/2.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 1.3,
                fuelType: 'Бензин',
                horsePower: 163,
                transmission: 'АКПП робот',
                driveType: 'Передний',
                color: '',
                generation: '200',
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '23',
            brand: 'Volkswagen',
            model: 'Golf',
            year: 2020,
            category: 'Хэтчбеки',
            price: 1950000,
            images: [
                '/img/catalog/eu/WV-GOLF/1.jpg',
                '/img/catalog/eu/WV-GOLF/2.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 1.4,
                fuelType: 'Бензин',
                horsePower: 150,
                transmission: 'АКПП робот',
                driveType: 'Передний',
                color: '',
                generation: '280 TSI DSG PRO',
                features: [
                    'Подогрев руля',
                    'Люк',
                    'Обогрев зеркал',
                    'Беспроводная зарядка',
                ],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '24',
            brand: 'Volkswagen',
            model: 'TiguanL',
            year: 2021,
            category: 'Кроссоверы',
            price: 3235000,
            images: [
                '/img/catalog/eu/Volkswagen-TiguanL/1.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/2.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 220,
                transmission: 'АКПП робот',
                driveType: '4WD',
                color: '',
                generation: '1 поколение, рестайлинг',
                features: ['2.0 380 TSI DSG R-Line Flagship'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '25',
            brand: 'Skoda',
            model: 'Kamiq',
            year: 2022,
            category: 'Седаны',
            price: 1335000,
            images: [
                '/img/catalog/eu/Skoda-Kamiq/1.jpg',
                '/img/catalog/eu/Skoda-Kamiq/2.jpg',
            ],
            specs: {
                mileage: 12000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 109,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Белый',
                generation: '1 поколение, рестайлинг',
                features: ['2.0 380 TSI DSG R-Line Flagship'],
            },
            available: true,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
}
